### ISSUE TITLE
dwc:speciesProfile isExtinct not interpreted

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#1141] opened 2022-04-20 11:15 UTC
The DWC speciesProfile extensions `isExtinct` field does not seem to mark a species as extinct in CLB:
https://www.dev.checklistbank.org/dataset/131219/taxon/106425

**Comment by mdoering** [comment] 2022-04-21 09:40
Yes, the entire extension is not yet supported.

**Comment by mdoering** [comment] 2022-04-21 09:42
duplicate of #747

**Closed by mdoering** 2022-04-21 09:42 UTC
Labels: importer, feature request
