### ISSUE TITLE
User registration fails with GBIF username

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1133] opened 2022-03-28 21:30 UTC
We might have hit a bug with the user registration process in which the user has to use their email address the first time they login. Otherwise they get a 401 basic authentication error with this [stack trace](https://logs.gbif.org/app/discover#/context/37c669c0-2a5c-11eb-9ca0-ddc1af98892f/aN1a0n8BOejCygyA9exf?_g=(filters:!())&_a=(columns:!(level,logger_name,message),filters:!())):

```
java.lang.IllegalArgumentException: User NicBailly does not exist
	at life.catalogue.dw.auth.IdentityService.get(IdentityService.java:83)
	at life.catalogue.dw.auth.IdentityService.authenticate(IdentityService.java:156)
	at life.catalogue.dw.auth.AuthFilter.doBasic(AuthFilter.java:229)
	at life.catalogue.dw.auth.AuthFilter.filter(AuthFilter.java:80)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:108)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:44)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:173)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:247)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:47)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:41)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:313)
	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Once they login with their email address, they seem to be able to login with the username.

Alternatively, it might be an issue with username case sensitivity during registration, because he was trying to login with NicBailly and the backend shows it as all [lowercase](https://api.catalogueoflife.org/user/351) and when he switched to camelCase the login worked but that was after he used his email address to successfully register.

**Comment by mdoering** [comment] 2022-03-28 21:51
I am not sure if I understand what happened. There are 2 Baillys in the system `nicbailly` and a much older `nbailly`.
I assume it's the nicbailly account that had problems. He did have a GBIF account `NicBailly` that he used to log into CLB for the first time. Using his username `NicBailly` resulted in aboves error? But when he logged in with his email it worked?

**Comment by gdower** [comment] 2022-03-28 22:02
I think he lost access to the older account and couldn't recover it.

He hadn't logged into the prod server yet with NicBailly, and that's when he generated the above stack trace in the logs. I had him try again with his email address, and then after seeing that stack trace I asked him to log out and login with the username which he did with `nicBailly` and that worked. So I think either the GBIF registration IdentityService might be case sensitive or there's a new bug that requires logging in with an email address the first time.

**Comment by mdoering** [comment] 2022-03-29 08:33
A few remarks on how authentication works:
 - the GBIF account must be working - try it on the GBIF portal 
 - only the username is accepted, never the email
 - username is case insensitive 
 - other auth methods supported by GBIF like facebook, google, orcid are not yet supported by us
 - there is hardly any difference in logging in for the first time than subsequent log ins

**Comment by mdoering** [comment] 2022-03-29 08:35
As we moved to a new postgres14 server on march 23rd we could have missed first time log ins during a few hours on that day. This would explain the above error. It was inserted into the old still live pg13 db, we then switched 4 hours later and lost the new users during that time period. Any chance this happened then?

**Comment by mdoering** [comment] 2022-03-29 08:37
I would close the issue as I cannot reproduce it and it might be related to the migration. Please reopen if you think differently

**Closed by mdoering** 2022-03-29 08:37 UTC
