### ISSUE TITLE
status 500 errors when fetching sectors for dataset 3LRC

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#897] opened 2020-10-30 15:42 UTC
<img width="1060" alt="sector_status_500" src="https://user-images.githubusercontent.com/1666484/97725803-dc81a080-1ace-11eb-8bc5-27082df7f067.png">

**Comment by mdoering** [comment] 2020-10-30 16:20
works fine for me. But its probably cached by now

**Comment by mdoering** [comment] 2020-10-30 16:38
cant reproduce now, so closing. Please reopen when its back

**Closed by mdoering** 2020-10-30 16:38 UTC
