### ISSUE TITLE
subjectDatasetKey inconsistency for dataset 3LR

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#878] opened 2020-10-16 08:11 UTC
The tree has dataset 1008 as sector source here:
https://www.dev.catalogue.life/?taxonKey=fa9c40ab-7a82-42a6-8bad-6850141ed1a6

But that dataset is missing as a source: https://www.dev.catalogue.life/data/dataset/1008

**Comment by mdoering** [comment] 2020-10-16 08:27
duplicate of #869

**Closed by mdoering** 2020-10-16 08:27 UTC
