### ISSUE TITLE
What's happened to metadata patch?

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1017] opened 2021-06-07 16:19 UTC
Frontend version: c9d812c June 1, 2021 7:49 AMBackend version: e6a2cb9 May 16, 2021 11:19 PM

Updated GSD Scarabs, id1027. **Version and date should be 2021-06-01**

For attention of @mdoering @thomasstjerne (FYI @gdower)

_Master metadata (correct date shown):_
https://data.catalogueoflife.org/dataset/1027/metadata
![image](https://user-images.githubusercontent.com/28574252/121053499-0e539780-c781-11eb-9fc4-f2be7d7a518f.png)

_Patch:_ 
https://data.catalogueoflife.org/catalogue/3/dataset/1027/metadata

View before actions (incorrect date shown):
![image](https://user-images.githubusercontent.com/28574252/121053799-57a3e700-c781-11eb-92ef-b7348d114fea.png)

Patch edited as "NULL". Does it mean, expected an empty patch, and date should be passed from the master metadata?
![image](https://user-images.githubusercontent.com/28574252/121054348-e0bb1e00-c781-11eb-9b56-69ed577250e7.png)
Saved.

However, incorrect dates on the page shown as: 
![image](https://user-images.githubusercontent.com/28574252/121054509-0811eb00-c782-11eb-891f-77a1f6434ee2.png)

**Comment by yroskov** [comment] 2021-06-07 16:48
The same problem I have had today with a version & date in ITIS metadata. As [bad] result, included a new dates in a patch. Expected behavior: patch (null?) translates version & date from master metadata.

**Comment by yroskov** [comment] 2021-06-07 16:59
Another variant of the action with a patch:

Patch with empty version and date fields; NULL button was nor activated:
![image](https://user-images.githubusercontent.com/28574252/121059929-a2286200-c787-11eb-8d19-3f83f098c1b4.png)
Saved.

The same result on the page (incorrect date from previous update): 
![image](https://user-images.githubusercontent.com/28574252/121060025-b8ceb900-c787-11eb-8b84-dca55e3daaba.png)

**Comment by mdoering** [comment] 2021-06-07 19:03
... as mentioned various times, setting the patch to `NULL` is not implemented properly yet. We all decided it was not a priority. Once done, it will allow to remove a value from the source and replace it with nothing.

**Comment by thomasstjerne** [comment] 2021-06-08 09:29
duplicate of https://github.com/CatalogueOfLife/checklistbank/issues/845

**Closed by thomasstjerne** 2021-06-08 09:29 UTC
