### ISSUE TITLE
Misinterpreted names in Clearinghouse

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#849] opened 2020-09-21 18:54 UTC
Frontend version: 0e34f62 September 18, 2020 2:04 AMBackend version: ce3a5b1 September 18, 2020 2:34 AM
@mdoering @gdower 

Working with Issues in World Plants on prod...

There are names which are misinterpreted names by the Clearinghouse:

- [x] _Blacklisted epithet_
https://data.catalogue.life/catalogue/3/dataset/1141/workbench?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=blacklisted%20epithet&limit=100&offset=0

**Laurus till Poir.** - absolutely correct name.

- [ ] _Subspecies assigned_
https://data.catalogue.life/catalogue/3/dataset/1141/workbench?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=subspecies%20assigned&limit=100&offset=0

![image](https://user-images.githubusercontent.com/28574252/93804602-2cd22c80-fc0c-11ea-8948-75cce8f4d0c9.png)

Mistake in the source data: **Linum hellenicum latrou** should be **Linum hellenicum Iatrou** I, not L  - reported to MH.

Crawler or Clearinghouse or both?: **Ludwigia peduncularis dela Maza**;  in the source **Ludwigia peduncularis (C. Wright ex Griseb.) G&oacute;mez dela Maza**

**Papaver victoris kornik Å** ;  in the source **Papaver victoris Škornik & Wraber**

**Taraxacum triangulare fl H. Lindb.**; in the source **Taraxacum triangulare H. Lindb. fl**

**_Corrections in the Clearinghouse (complex decision) are failed._**

**Comment by yroskov** [comment] 2020-09-21 19:02
Accepted ID invalid      @gdower, could you pls have a look on this 

https://data.catalogue.life/catalogue/3/dataset/1141/verbatim?issue=accepted%20id%20invalid

**Comment by yroskov** [comment] 2020-09-21 19:15
- [ ] _Unmatched name brackets_
https://data.catalogue.life/catalogue/3/dataset/1141/workbench?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=unmatched%20name%20brackets&limit=100&offset=0

Crawler or Clearinghouse?: 
In the pattern _(Author1 **at al.)** Author2_ right bracket is missing.

![image](https://user-images.githubusercontent.com/28574252/93810810-cac9f500-fc14-11ea-9c99-8f0c3b1a9730.png)

**Comment by yroskov** [comment] 2020-09-21 19:20
- [ ] _Authorship Contains Nomenclatural Note_
https://data.catalogue.life/catalogue/3/dataset/1141/workbench?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=authorship%20contains%20nomenclatural%20note&limit=100&offset=0

Crawler or Clearinghouse?: word "ined." repeated twice; in the source: Xylocalyceae ined.

**Comment by yroskov** [comment] 2020-09-21 19:23
- [ ] _Name ID invalid_ 
https://data.catalogue.life/catalogue/3/dataset/1141/verbatim?issue=name%20id%20invalid

@gdower could you pls have a look

**Comment by yroskov** [comment] 2020-09-21 19:29
- [ ] Name Match None
https://data.catalogue.life/catalogue/3/dataset/1141/workbench?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&issue=name%20match%20none&limit=100&offset=0

YR: Decisions do not work today. **More names need to be blocked.**

**Comment by yroskov** [comment] 2020-09-21 19:30
- [ ] _Parent Name Mismatch_

**Comment by mdoering** [comment] 2020-09-21 21:16
Thanks Yuri. A lot of different issues here. It would be simpler to read and follow if you could keep the issue summarised at the very top. Starting from there:

**Laurus till Poir.**
Blacklisted because `till` is in the blacklisted epithet list:
https://github.com/gbif/name-parser/blob/master/name-parser/src/main/resources/nameparser/blacklist-epithets.txt#L201

I'm not sure if a blacklisted name has any consequences in our assembly. It might get blocked, but probably it doesnt. I take it more as a hint to look closely.

**Subspecies assigned**
In general if you are not sure if it's an artefact of the Clearinghouse (aka ChecklistBank) or the source one needs to check the verbatim data. This is exactly a use case it was designed for. To make sure the interpretation of the data in ChecklistBank is correct we keep a copy of the exact verbatim data:

[Linum hellenicum latrou](https://data.catalogue.life/catalogue/3/dataset/1141/verbatim?type=col:Name&col:ID=374d7d4a-e091-5121-83df-46e7fffc8c0e&termOp=OR) comes in as an infraspecific name:

<img width="1073" alt="Screenshot 2020-09-21 at 22 22 27" src="https://user-images.githubusercontent.com/327505/93817244-f5d63800-fc58-11ea-8930-c88b77c4bcf6.png">

I assume the same is true for the others.

**Unmatched name brackets**
See verbatim, e.g. [Cerastium ligusticum subsp. granulatum (Huter et al. P. D. Sell & Whitehead](https://data.catalogue.life/catalogue/3/dataset/1141/verbatim?type=col:Name&col:ID=de766747-7ac9-542b-9ca9-b56deead7269&termOp=OR)

> Cerastium ligusticum subsp. granulatum (Huter et al.) P. D. Sell & Whitehead
Looks like this indeed could be a name parser bug!

**Comment by mdoering** [comment] 2020-09-21 21:20
**Eucnidoideae ined.**

Looks also like an interpretation bug. Maybe because `ined.` is given in both scientificName and authorship:
> Eucnidoideae ined.

**Comment by yroskov** [comment] 2020-09-21 21:58
> Blacklisted epithet  in Laurus till

Yeah, "Laurus till" passed in the CoL. All are OK.

**Comment by mdoering** [comment] 2020-09-22 12:57
- [x] blacklisted `till` kept as it doesn't hurt
 - [x] Eucnidoideae ined. fixed
 - [ ] Unmatched name brackets

**Comment by mdoering** [comment] 2020-09-22 18:33
The unmatched brackets problem was with et al. names in brackets. Its fixed in dev now, deploying to prod early tomorrow

**Comment by mdoering** [comment] 2020-09-22 18:38
Yuri, please reopen if I missed sth other important from the backend importer/interpretions

**Closed by mdoering** 2020-09-22 18:38 UTC
