### ISSUE TITLE
ClassCastException on import of DwC archive

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#783] opened 2020-07-13 12:24 UTC
<img width="1092" alt="Screenshot at Jul 13 14-23-39" src="https://user-images.githubusercontent.com/1666484/87304069-86372480-c514-11ea-9cca-c9e9c5cbbfc7.png">

ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')

**Comment by thomasstjerne** [comment] 2020-07-13 12:24
This was in PROD env

**Comment by mdoering** [comment] 2020-07-16 05:56
duplicate of #785

**Closed** 2020-07-16 06:37 UTC
Labels: duplicate
