### ISSUE TITLE
Multiword monomial, Wrong monomial case issues not showing in individual datasets

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/backend#1377] opened 2024-11-16 00:58 UTC
The [DAISIE ](https://www.checklistbank.org/dataset/25428/issues) dataset has several names with the issue Multi Word Monomial that were only shown as issue on the [xRelease](https://www.checklistbank.org/dataset/305087/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&issue=multi%20word%20monomial&limit=50&offset=0). 

This issue could be added in the `issueExclusion:` of the xrelease config file to avoid including this kind of names.

**Comment by camiplata** [comment] 2024-11-16 04:07
duplicate of https://github.com/CatalogueOfLife/backend/issues/1376

**Closed** 2024-11-18 09:58 UTC
