### ISSUE TITLE
Error after attempt to save edited metadata

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1041] opened 2021-08-19 17:42 UTC
https://data.catalogueoflife.org/dataset/1146/about

I have edited metadata for CrabCat, id 1146. After I pushed Save button, I have got following error message (422):

![image](https://user-images.githubusercontent.com/28574252/130117700-1d1e2d8e-baa2-4dca-aea0-89b4f0962882.png)

**Comment by mdoering** [comment] 2021-08-19 18:24
duplicate of #1040

**Closed by mdoering** 2021-08-19 18:24 UTC
Labels: bug
