### ISSUE TITLE
DOI issues on GBIF sync job

### ISSUE THREAD

**Issue by timrobertson100** [CatalogueOfLife/backend#1194] opened 2023-02-01 07:48 UTC
Running the indexing step of the COL release gives a lot of these kind of logs

```
! ### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "dataset_doi_key"
!   Detail: Key (doi)=(10.5962/bhl.title.542) already exists.
! ### The error occurred while setting parameters
! ### SQL: INSERT INTO dataset (key,            type,           doi,     identifier,     title,     alias,     description,     issued,     version,     issn,     contact,     creator,     editor,     publisher,     contributor,     keyword,     geographic_scope,     taxonomic_scope,     temporal_scope,     confidence,     completeness,     license,     url,     logo,     notes,     created_by,     modified_by        ,     deleted,     gbif_key,     gbif_publisher_key,     private    , source_key, origin, created, modified, acl_editor)     VALUES (?,            ?::datasettype,          ?,     ?::hstore,     ?,     ?,     ?,     ?,     ?,     ?,     ?,     ?,     ?,     ?,     ?,     ?,     ?,     ?,     ?,     ?,     ?,     ?::LICENSE,     ?,     ?,     ?,     ?,     ?    ,     ?,     ?,     ?,     ?    , ?, ?::DATASETORIGIN, now(), now(),                          NULL                        )
! ### Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "dataset_doi_key"
```

I am not sure if this is expected, but if so, can we fix up logging to aid those trying to diagnose issues please?

**Comment by mdoering** [comment] 2023-02-06 14:05
Are you sure this stems from a release? These should come from the GBIF registry sync and are expected due to non unique DOIs registered in GBIF: https://github.com/gbif/registry/issues/465

Closing as a duplicate of https://github.com/CatalogueOfLife/data/issues/496

**Closed by mdoering** 2023-02-06 14:05 UTC

**Comment by timrobertson100** [comment] 2023-02-06 14:26
FWIW I think this could be improved in checklistbank code as well as being addressed in the data process. 

The logs are distracting for people who are looking for other issues. Better would be a log statement `WARN: Duplicate DOI dataset found syncing with GBIF (DOI: 1234). Ignoring dataset (perhaps relates to gbif/registry#465)` without the stacktrace.
