### ISSUE TITLE
CLB: blank sector in the report on ITIS sectors - it's not flagged as a broken

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#1105] opened 2022-02-16 16:16 UTC
CLB on PROD
[Frontend version: 1bb80f5 February 11, 2022 1:19 PM](https://github.com/CatalogueOfLife/checklistbank/tree/1bb80f5)[Backend version: c94dbef February 15, 2022 12:00 AM](https://github.com/CatalogueOfLife/backend/tree/c94dbef)

@mdoering, @thomasstjerne 

There is a strange case of blank sector in ITIS. It looks like that:
![image](https://user-images.githubusercontent.com/28574252/154295275-e8c3e169-aa08-4baa-ac07-051ed7cb3f5b.png)

There are no broken sectors in ITIS according to the report.

My attempt to re-match blank sector in Coleoptera failed and pop-up menu reported "broken sector". However, the sector is not flagged as "broken" in the report on ITIS sectors. 

(Now ITIS report is down completely, see https://github.com/CatalogueOfLife/checklistbank/issues/1007)

**Comment by mdoering** [comment] 2022-02-16 16:38
duplicate of https://github.com/CatalogueOfLife/checklistbank/issues/1007

**Closed by mdoering** 2022-02-16 16:38 UTC
