### ISSUE TITLE
500 errors on importer: Error attempting to get column 'verbatim_by_row_type_count' from result set

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#967] opened 2021-02-26 14:10 UTC
With the new deployment, the backend is throwing 500 errors on the importer endpoint.

Frontend version: 2af1748 February 17, 2021 8:00 AM
Backend version: 15bca9a February 25, 2021 8:12 AM

[Logs](https://logs.gbif.org/app/discover#/context/37c669c0-2a5c-11eb-9ca0-ddc1af98892f/y3Cl3ncBU86CouzbU0ZP?_a=(columns:!(level,datasetKey,service,logger_name,message),filters:!())&_g=(filters:!())): 
```
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.apache.ibatis.executor.result.ResultMapException: Error attempting to get column 'verbatim_by_row_type_count' from result set.  Cause: java.lang.IllegalArgumentException: The simple name is required
### The error may exist in life/catalogue/db/mapper/DatasetImportMapper.xml
### The error may involve life.catalogue.db.mapper.DatasetImportMapper.list
### The error occurred while handling results
### SQL: SELECT       dataset_key,     attempt,     state,           job,     error,     started,     finished,     created_by,     applied_decision_count,     bare_name_count,     distribution_count,     estimate_count,     media_count,     name_count,     reference_count,     synonym_count,     taxon_count,     treatment_count,     type_material_count,     vernacular_count,     distributions_by_gazetteer_count,     extinct_taxa_by_rank_count,     ignored_by_reason_count,     issues_by_issue_count,     media_by_type_count,     name_relations_by_type_count,     names_by_code_count,     names_by_rank_count,     names_by_status_count,     names_by_type_count,     species_interactions_by_type_count,     synonyms_by_rank_count,     taxa_by_rank_count,     taxon_concept_relations_by_type_count,     type_material_by_status_count,     usages_by_origin_count,     usages_by_status_count,     vernaculars_by_language_count    ,     md5,     download_uri,     download,     format,     origin,     verbatim_count,     verbatim_by_term_count,     verbatim_by_row_type_count         FROM       dataset_import di                WHERE  di.state IN         (           ?::IMPORTSTATE         ,           ?::IMPORTSTATE         ,           ?::IMPORTSTATE         ,           ?::IMPORTSTATE         )          ORDER BY di.started DESC, di.attempt DESC, di.dataset_key                       LIMIT ? OFFSET ?
### Cause: org.apache.ibatis.executor.result.ResultMapException: Error attempting to get column 'verbatim_by_row_type_count' from result set.  Cause: java.lang.IllegalArgumentException: The simple name is required
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy118.list(Unknown Source)
	at life.catalogue.dao.DatasetImportDao.list(DatasetImportDao.java:60)
	at life.catalogue.importer.ImportManager.listImports(ImportManager.java:137)
	at life.catalogue.resources.ImporterResource.list(ImporterResource.java:50)
	at jdk.internal.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:50)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:47)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:41)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:249)
	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:767)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.ibatis.executor.result.ResultMapException: Error attempting to get column 'verbatim_by_row_type_count' from result set.  Cause: java.lang.IllegalArgumentException: The simple name is required
	at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:83)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getPropertyMappingValue(DefaultResultSetHandler.java:472)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.applyPropertyMappings(DefaultResultSetHandler.java:441)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getRowValue(DefaultResultSetHandler.java:404)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValuesForSimpleResultMap(DefaultResultSetHandler.java:354)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValues(DefaultResultSetHandler.java:328)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSet(DefaultResultSetHandler.java:301)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:194)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 71 common frames omitted
Caused by: java.lang.IllegalArgumentException: The simple name is required
	at org.gbif.dwc.terms.UnknownTerm.<init>(UnknownTerm.java:88)
	at org.gbif.dwc.terms.UnknownTerm.build(UnknownTerm.java:24)
	at org.gbif.dwc.terms.TermFactory.createUnknownTerm(TermFactory.java:256)
	at org.gbif.dwc.terms.TermFactory.findTerm(TermFactory.java:195)
	at life.catalogue.api.jackson.TermSerde$TermKeyDeserializer.deserializeKey(TermSerde.java:31)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBind(MapDeserializer.java:449)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:367)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1261)
	at life.catalogue.db.type2.NestedTermMapTypeHandler.fromJson(NestedTermMapTypeHandler.java:59)
	at life.catalogue.db.type2.NestedTermMapTypeHandler.getNullableResult(NestedTermMapTypeHandler.java:43)
	at life.catalogue.db.type2.NestedTermMapTypeHandler.getNullableResult(NestedTermMapTypeHandler.java:21)
	at org.apache.ibatis.type.BaseTypeHandler.getResult(BaseTypeHandler.java:81)
	... 85 common frames omitted
```

**Comment by mdoering** [comment] 2021-02-26 14:17
thats weird. It didnt show up on dev before. I'll check

**Comment by gdower** [comment] 2021-02-26 14:43
We do actually hit the bug on page 3 of the importer queue for dev, so probably it's one of the dataset types causing it. Maybe private datasets or a release?

https://data.dev.catalogueoflife.org/imports/finished?limit=10&offset=20&state=unchanged&state=finished&state=canceled&state=failed

**Comment by mdoering** [comment] 2021-02-26 20:03
fixed the problem in the database, code is about to be committed so it doesn't happen again.
It is caused by the way we (wrongly) serialised BibTex terms in dataset import metrics. Rather specific and always been like this in the code, but we never had BibTex files in archives before so it did not show up. The Leipzig LCVP dataset did have bibtex for the first time, that caused it.

**Closed** 2021-02-26 20:08 UTC
Labels: bug
